# Generated by perplexity.ai

import cv2
from morph_contour_demo import Timer

# Create a VideoCapture object to capture video from the camera
cap = cv2.VideoCapture(0)

timer = Timer()

# Check if camera opened successfully
if not cap.isOpened():
    print("Error opening video stream or file")

# Read until the user quits the program
while cap.isOpened():
    # Capture frame-by-frame
    ret, frame = cap.read()
    timer.inc()
    if ret:
        print("Grabbed")
    else:
        break

print(timer.elapsed())
# Release the VideoCapture object and close all windows
cap.release()
